// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Gq1_7xnYttMqittT8Wi1ELvKUCn8wvo',
    appId: '1:240984470169:web:8a0c921d1d0c248c8f7e08',
    messagingSenderId: '240984470169',
    projectId: 'translation-8ff8f',
    authDomain: 'translation-8ff8f.firebaseapp.com',
    storageBucket: 'translation-8ff8f.firebasestorage.app',
    measurementId: 'G-S2VJSGSQ2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-g2WjfhA8Qh9iZr4w-BV45PU5vY7jM_E',
    appId: '1:240984470169:android:3fb52a5a43c899858f7e08',
    messagingSenderId: '240984470169',
    projectId: 'translation-8ff8f',
    storageBucket: 'translation-8ff8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_kD3x3ygdj86KihdCiRNJc3bDSTEl5_M',
    appId: '1:240984470169:ios:00ee09b7d122ed268f7e08',
    messagingSenderId: '240984470169',
    projectId: 'translation-8ff8f',
    storageBucket: 'translation-8ff8f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_kD3x3ygdj86KihdCiRNJc3bDSTEl5_M',
    appId: '1:240984470169:ios:00ee09b7d122ed268f7e08',
    messagingSenderId: '240984470169',
    projectId: 'translation-8ff8f',
    storageBucket: 'translation-8ff8f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Gq1_7xnYttMqittT8Wi1ELvKUCn8wvo',
    appId: '1:240984470169:web:92afc3402994e0438f7e08',
    messagingSenderId: '240984470169',
    projectId: 'translation-8ff8f',
    authDomain: 'translation-8ff8f.firebaseapp.com',
    storageBucket: 'translation-8ff8f.firebasestorage.app',
    measurementId: 'G-2Q9DX995S9',
  );
}
